# Generated by Django 4.1.7 on 2023-03-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavedays',
            old_name='EmpId',
            new_name='Emp_Id',
        ),
    ]
