# Generated by Django 4.1.7 on 2023-03-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0002_rename_empid_leavedays_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavedays',
            old_name='Emp_Id',
            new_name='EmpId',
        ),
    ]
