# Generated by Django 4.1.7 on 2023-03-11 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DOB', models.DateField(null=True)),
                ('PhoneNumber', models.IntegerField(null=True)),
                ('IDnumber', models.IntegerField(null=True)),
                ('KRAPIN', models.CharField(max_length=255, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Role', models.CharField(max_length=255, null=True)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('Email_verified', models.BooleanField(default=False)),
                ('Verification_token', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDays',
            fields=[
                ('EmployeeId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hrsystem.employee')),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Description', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('AssetId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AssetName', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Assigned_status', models.BooleanField(default=False)),
                ('EmployeeId', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrsystem.employee')),
            ],
        ),
    ]
