# Generated by Django 4.1.7 on 2023-03-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='d',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
