# Generated by Django 4.1.7 on 2023-03-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
