# Generated by Django 4.1.7 on 2023-03-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0002_assets_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='d',
        ),
    ]
