# Generated by Django 4.1.7 on 2023-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0002_alter_employee_options_employee_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Verification_token',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
