# Generated by Django 4.1.7 on 2023-03-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0003_alter_employee_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='PhoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
