# Generated by Django 4.1.7 on 2023-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0003_rename_emp_id_leavedays_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedays',
            name='Status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
