# Generated by Django 4.1.7 on 2023-03-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrsystem', '0005_rename_assigned_status_assets_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EmpId', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
